//  Generated by entity-cli
import {
  Entity,
  Column,
  CreateDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  BaseEntity,
  ManyToOne,
} from "typeorm";
import { TypeTheme } from "../../type-theme/entities/type-theme.entity";

@Entity()
export class Theme extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  createDate: Date;

  @UpdateDateColumn()
  updateDate: Date;
  @Column({ type: "varchar" })
  libelle: string;

  @ManyToOne((type) => TypeTheme, (typetheme) => typetheme.themes)
  typetheme: TypeTheme;
}
