//  Generated by entity-cli
import {
  Entity,
  Column,
  CreateDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  BaseEntity,
  OneToMany,
} from "typeorm";
import { Theme } from "../../theme/entities/theme.entity";

@Entity()
export class TypeTheme extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  createDate: Date;

  @UpdateDateColumn()
  updateDate: Date;
  @Column({ type: "varchar" })
  libelle: string;
  @OneToMany((type) => Theme, (theme) => theme.typetheme)
  themes: Theme[];
}
