//  Generated by entity-cli
import {
  Entity,
  Column,
  CreateDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  BaseEntity,
  ManyToOne,
} from "typeorm";
import { Article } from "../../article/entities/article.entity";

@Entity()
export class Categorie extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  createDate: Date;

  @UpdateDateColumn()
  updateDate: Date;
  @Column({ type: "varchar" })
  libelle: string;

  @ManyToOne((type) => Article, (article) => article.categories)
  article: Article;
}
